'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, Brain, Download, Copy, Play, CheckCircle2, RefreshCw } from 'lucide-react'
import Link from 'next/link'

export default function AIGeneratorPage() {
  const [topic, setTopic] = useState('')
  const [classVal, setClassVal] = useState('Class 12')
  const [board, setBoard] = useState('CBSE')
  const [format, setFormat] = useState('MCQ Quiz') // 'MCQ Quiz', 'Formula Sheet', 'Detailed Summary'
  const [difficulty, setDifficulty] = useState('Medium')
  
  const [loading, setLoading] = useState(false)
  const [generatedOutput, setGeneratedOutput] = useState<any>(null)
  const [copied, setCopied] = useState(false)

  const handleGenerate = () => {
    if (!topic.trim()) return
    setLoading(true)
    setGeneratedOutput(null)

    setTimeout(() => {
      setLoading(false)
      if (format === 'MCQ Quiz') {
        setGeneratedOutput({
          title: `Generated MCQ Quiz: ${topic}`,
          type: 'quiz',
          items: [
            { q: `Which of the following describes the key mechanism of ${topic}?`, o: ['Option Alpha', 'Option Beta (Correct)', 'Option Gamma', 'Option Delta'], a: 1 },
            { q: `What is the primary constraint associated with ${topic} systems?`, o: ['Temperature dependence', 'Pressure limits', 'Voltage degradation', 'All of the above'], a: 3 }
          ]
        })
      } else if (format === 'Formula Sheet') {
        setGeneratedOutput({
          title: `${topic} Formula Sheet`,
          type: 'formulas',
          items: [
            { name: `${topic} Efficiency coefficient`, eq: 'η = (Work Output / Heat Input) * 100%' },
            { name: `Generalized state relation`, eq: 'P * V^γ = Constant' }
          ]
        })
      } else {
        setGeneratedOutput({
          title: `${topic} Study Guide Summary`,
          type: 'summary',
          text: `Here is a comprehensive summary generated by Gemini AI for: ${topic}.\n\nOverview:\n${topic} represents a fundamental component of the curriculum. It integrates various physical laws and chemical reactions dependent on environment state.\n\nKey Takeaways:\n1. Theoretical formulations are governed by conservation laws.\n2. Empirical calculations confirm correlation in testing parameters.\n3. Defect rates decline when temperatures remain stable.`
        })
      }
    }, 2000)
  }

  const handleCopy = () => {
    setCopied(true)
    navigator.clipboard.writeText(JSON.stringify(generatedOutput, null, 2))
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <main className="min-h-screen bg-midnight-900 text-white relative overflow-hidden">
      {/* Background grid */}
      <div className="absolute inset-0 cyber-grid opacity-30" />
      <div className="absolute top-20 left-10 w-96 h-96 rounded-full bg-cyan-400/5 blur-3xl" />
      
      {/* Header navbar */}
      <header className="fixed top-0 left-0 right-0 z-50 glass-strong py-4 px-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400/20 to-cyan-600/20 
                            flex items-center justify-center glow-border">
              <span className="text-xl font-bold gradient-text">S</span>
            </div>
            <span className="text-xl font-bold">
              Stat<span className="text-cyan-400">Xam</span>
            </span>
          </Link>
          <Link href="/dashboard" className="px-6 py-2.5 rounded-xl border border-cyan-400/50 text-cyan-400 font-semibold flex items-center gap-2 hover:bg-cyan-400/10 transition-all text-xs">
            Go to Dashboard
          </Link>
        </div>
      </header>

      {/* Main Form container */}
      <section className="pt-32 pb-20 px-6 max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8 relative z-10">
        <div className="lg:col-span-5 bg-white/5 border border-white/10 p-6 rounded-3xl glow-hover flex flex-col justify-between space-y-6 h-fit">
          <div>
            <div className="flex items-center gap-2 px-3 py-1 bg-cyan-400/10 border border-cyan-400/20 text-xs font-semibold text-cyan-400 rounded-full w-fit">
              <Sparkles className="w-3.5 h-3.5" />
              Gemini Question Generator
            </div>
            <h1 className="text-2xl font-extrabold text-white mt-4">AI Study Material Generator</h1>
            <p className="text-xs text-gray-400 mt-1">Generate customized practice quizzes, formulas, sheets, and guides instantly.</p>
          </div>

          <div className="space-y-4">
            <div>
              <label className="text-xs text-gray-400 font-bold block mb-1.5">Topic or Chapter Name</label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Electrostatics, Thermodynamics, Cell Division"
                className="w-full h-10 px-3 bg-midnight-900 border border-white/10 rounded-xl text-sm focus:outline-none focus:border-cyan-400/50 text-white"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs text-gray-400 font-bold block mb-1.5">Class</label>
                <select 
                  value={classVal} 
                  onChange={(e) => setClassVal(e.target.value)}
                  className="w-full h-10 px-3 bg-midnight-900 border border-white/10 rounded-xl text-sm focus:outline-none focus:border-cyan-400/50 text-white text-xs font-semibold"
                >
                  <option>Class 10</option>
                  <option>Class 11</option>
                  <option>Class 12</option>
                  <option>JEE/NEET</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-gray-400 font-bold block mb-1.5">Board</label>
                <select 
                  value={board} 
                  onChange={(e) => setBoard(e.target.value)}
                  className="w-full h-10 px-3 bg-midnight-900 border border-white/10 rounded-xl text-sm focus:outline-none focus:border-cyan-400/50 text-white text-xs font-semibold"
                >
                  <option>Andhra Pradesh Board</option>
                  <option>Bihar School Examination Board (BSEB)</option>
                  <option>Central Board of Secondary Education (CBSE)</option>
                  <option>Chhattisgarh Board (CGBSE)</option>
                  <option>Council for the Indian School Certificate Examinations (CISCE)</option>
                  <option>Gujarat Secondary and Higher Secondary Education Board (GSEB)</option>
                  <option>Haryana Board (BSEH)</option>
                  <option>Jharkhand Academic Council (JAC)</option>
                  <option>Karnataka Secondary Education Examination Board (KSEEB)</option>
                  <option>Kerala Board (DHSE / SCERT)</option>
                  <option>Madhya Pradesh Board (MPBSE)</option>
                  <option>Maharashtra State Board (MSBSHSE)</option>
                  <option>National Institute of Open Schooling (NIOS)</option>
                  <option>Odisha Board (BSE Odisha)</option>
                  <option>Punjab School Education Board (PSEB)</option>
                  <option>Rajasthan Board (RBSE)</option>
                  <option>Tamil Nadu State Board</option>
                  <option>Telangana State Board</option>
                  <option>Uttar Pradesh Board (UPMSP)</option>
                  <option>West Bengal Board (WBBSE / WBCHSE)</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs text-gray-400 font-bold block mb-1.5">Format</label>
                <select 
                  value={format} 
                  onChange={(e) => setFormat(e.target.value)}
                  className="w-full h-10 px-3 bg-midnight-900 border border-white/10 rounded-xl text-sm focus:outline-none focus:border-cyan-400/50 text-white text-xs font-semibold"
                >
                  <option>MCQ Quiz</option>
                  <option>Formula Sheet</option>
                  <option>Detailed Summary</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-gray-400 font-bold block mb-1.5">Difficulty</label>
                <select 
                  value={difficulty} 
                  onChange={(e) => setDifficulty(e.target.value)}
                  className="w-full h-10 px-3 bg-midnight-900 border border-white/10 rounded-xl text-sm focus:outline-none focus:border-cyan-400/50 text-white text-xs font-semibold"
                >
                  <option>Easy</option>
                  <option>Medium</option>
                  <option>Hard</option>
                </select>
              </div>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading || !topic.trim()}
            className="w-full h-12 bg-cyan-400 hover:bg-cyan-300 text-midnight-900 font-extrabold rounded-2xl flex items-center justify-center gap-2 transition-all disabled:opacity-50 text-sm shadow-[0_0_20px_rgba(0,212,255,0.3)]"
          >
            {loading ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Brain className="w-5 h-5" />}
            Generate Content
          </button>
        </div>

        {/* Output window displays */}
        <div className="lg:col-span-7 bg-white/5 border border-white/10 p-6 rounded-3xl glow-hover min-h-[450px] flex flex-col justify-between relative overflow-hidden">
          <AnimatePresence mode="wait">
            {loading ? (
              // Generating state loader skeleton
              <motion.div 
                key="loader"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex-1 flex flex-col items-center justify-center space-y-4 py-20"
              >
                <div className="w-16 h-16 rounded-full border-4 border-cyan-400/30 border-t-cyan-400 animate-spin" />
                <h3 className="text-lg font-bold text-white">AI Engine computing data structures...</h3>
                <p className="text-xs text-gray-400">Synthesizing topic guidelines and curriculum benchmarks</p>
              </motion.div>
            ) : generatedOutput ? (
              // Output view
              <motion.div 
                key="output"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex-1 flex flex-col justify-between h-full space-y-6"
              >
                <div>
                  <div className="flex justify-between items-center border-b border-white/10 pb-4">
                    <h3 className="font-extrabold text-lg text-cyan-400">{generatedOutput.title}</h3>
                    <div className="flex gap-2">
                      <button onClick={handleCopy} className="p-2 bg-white/5 border border-white/10 rounded-xl text-gray-400 hover:text-white transition-all">
                        {copied ? <CheckCircle2 className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                      </button>
                      <button className="p-2 bg-white/5 border border-white/10 rounded-xl text-gray-400 hover:text-white transition-all">
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <div className="mt-6 space-y-6 overflow-y-auto max-h-[300px]">
                    {generatedOutput.type === 'quiz' && (
                      <div className="space-y-6">
                        {generatedOutput.items.map((item: any, i: number) => (
                          <div key={i} className="space-y-3">
                            <span className="text-sm font-bold text-white">Q{i+1}: {item.q}</span>
                            <div className="grid grid-cols-1 gap-2">
                              {item.o.map((opt: string, optI: number) => (
                                <div key={optI} className={`p-3 rounded-xl border text-xs text-left ${optI === item.a ? 'border-green-500/50 bg-green-500/10 text-green-400 font-bold' : 'border-white/10 bg-white/5 text-gray-300'}`}>
                                  {opt}
                                </div>
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    {generatedOutput.type === 'formulas' && (
                      <div className="grid grid-cols-1 gap-4">
                        {generatedOutput.items.map((form: any, i: number) => (
                          <div key={i} className="bg-white/5 border border-white/10 p-4 rounded-xl space-y-1">
                            <span className="text-xs text-gray-400 font-semibold">{form.name}</span>
                            <div className="font-mono text-cyan-400 font-bold text-sm">{form.eq}</div>
                          </div>
                        ))}
                      </div>
                    )}

                    {generatedOutput.type === 'summary' && (
                      <div className="text-sm text-gray-300 leading-relaxed whitespace-pre-line bg-white/5 border border-white/10 p-4 rounded-xl">
                        {generatedOutput.text}
                      </div>
                    )}
                  </div>
                </div>

                <div className="text-[10px] text-gray-500 font-semibold border-t border-white/10 pt-4 flex justify-between">
                  <span>Topic: {topic}</span>
                  <span>Class: {classVal} ({board})</span>
                </div>
              </motion.div>
            ) : (
              // Empty state
              <motion.div 
                key="empty"
                className="flex-1 flex flex-col items-center justify-center space-y-4 py-20 text-center"
              >
                <div className="w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center text-cyan-400 shadow-[0_0_15px_rgba(0,212,255,0.1)]">
                  <Sparkles className="w-6 h-6 animate-pulse" />
                </div>
                <div>
                  <h3 className="font-bold text-white">No content generated yet</h3>
                  <p className="text-xs text-gray-400 max-w-sm mt-1">Specify a topic and parameters on the left and click Generate to run our AI engine.</p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </section>
    </main>
  )
}
