'use client'

import { motion } from 'framer-motion'
import { ScrollText, FileText, ChevronRight } from 'lucide-react'

export default function NotesPage() {
  const notes = [
    { title: 'Electrostatics dipole derivations summary', date: 'Yesterday', subject: 'Physics' },
    { title: 'Thermodynamics critical formulas', date: '3 days ago', subject: 'Physics' },
    { title: 'Calculus substitution integration list', date: '1 week ago', subject: 'Mathematics' }
  ]

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
          My Saved <span className="text-blue-600">Notes</span>
        </h1>
        <p className="text-slate-500 text-sm mt-1">Access notes generated by AI assistant or bookmarked during study sessions.</p>
      </div>

      <div className="space-y-4">
        {notes.map((n, i) => (
          <div key={i} className="bg-white border border-slate-200/90 p-5 rounded-2xl flex justify-between items-center hover:border-blue-300 hover:shadow-card transition-all group cursor-pointer shadow-xs">
            <div className="flex gap-4 items-center">
              <div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center border border-blue-200/70 group-hover:border-blue-300 transition-colors shrink-0">
                <ScrollText className="w-6 h-6 text-blue-600" />
              </div>
              <div>
                <h4 className="font-bold text-slate-900 text-sm">{n.title}</h4>
                <div className="flex items-center gap-3 text-xs text-slate-500 mt-1 font-medium">
                  <span className="text-blue-700 font-semibold bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200/60">{n.subject}</span>
                  <span>Saved: {n.date}</span>
                </div>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-slate-400 group-hover:text-blue-600 transition-colors" />
          </div>
        ))}
      </div>
    </div>
  )
}
