'use client'

import { motion } from 'framer-motion'
import { ScrollText, FileText, ChevronRight } from 'lucide-react'

export default function NotesPage() {
  const notes = [
    { title: 'Electrostatics dipole derivations summary', date: 'Yesterday', subject: 'Physics' },
    { title: 'Thermodynamics critical formulas', date: '3 days ago', subject: 'Physics' },
    { title: 'Calculus substitution integration list', date: '1 week ago', subject: 'Mathematics' }
  ]

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">
          My Saved <span className="gradient-text">Notes</span>
        </h1>
        <p className="text-gray-400 text-sm mt-1">Access notes generated by AI assistant or bookmarked during study sessions.</p>
      </div>

      <div className="space-y-4">
        {notes.map((n, i) => (
          <div key={i} className="bg-white/5 border border-white/10 p-5 rounded-2xl flex justify-between items-center hover:border-cyan-400/40 transition-all group cursor-pointer">
            <div className="flex gap-4 items-center">
              <div className="w-12 h-12 rounded-xl bg-cyan-400/10 flex items-center justify-center border border-cyan-400/20 group-hover:border-cyan-400/50 transition-colors">
                <ScrollText className="w-6 h-6 text-cyan-400" />
              </div>
              <div>
                <h4 className="font-bold text-white text-sm">{n.title}</h4>
                <div className="flex items-center gap-3 text-xs text-gray-400 mt-1 font-semibold">
                  <span className="text-cyan-400">{n.subject}</span>
                  <span>Saved: {n.date}</span>
                </div>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400 group-hover:text-cyan-400 transition-colors" />
          </div>
        ))}
      </div>
    </div>
  )
}
